Controllers/NotificationController.cs
using AlphaZero.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AlphaZero.Controllers
{
    public class NotificationController : Controller
    {

        private db_roomrentalEntities db = new db_roomrentalEntities();

        // GET: Notification
        [ChildActionOnly]
        public ActionResult GetReminders()
        {
            var reminders = db.reminds.ToList();
            return PartialView("_Notifications", reminders);
        }

        // GET: User
        public ActionResult Index()
        {
            return View(db.reminds.ToList());
        }

        // GET: User/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            reminds reminds = db.reminds.Find(id);
            if (reminds == null)
            {
                return HttpNotFound();
            }
            return View(reminds);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Edit(int id)
        {
            reminds reminds = db.reminds.Find(id);
            return View(reminds);
        }

        [HttpPost]
        public ActionResult Edit(reminds reminds)
        {
            if (ModelState.IsValid)
            {
                // Retrieve the existing record based on the reminder_id
                reminds existingReminder = db.reminds.SingleOrDefault(i => i.reminder_id == reminds.reminder_id);

                if (existingReminder != null)
                {
                    existingReminder.reminder_title = reminds.reminder_title;
                    existingReminder.reminder_desc = reminds.reminder_desc;
                    existingReminder.reminder_date = reminds.reminder_date;

                    // Update the attributes only if landlord_id and tenant_id are null
                    if (reminds.landlord_id == null)
                    {
                        existingReminder.landlord_id = null;
                    }
                    else
                    {
                        existingReminder.landlord_id = reminds.landlord_id;
                    }

                    if (reminds.tenant_id == null)
                    {
                        existingReminder.tenant_id = null;
                    }
                    else
                    {
                        existingReminder.tenant_id = reminds.tenant_id;
                    }

                    db.Entry(existingReminder).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return RedirectToAction("Index");
            }

            return View(reminds);
        }



        [HttpPost]
        public ActionResult Create(reminds reminds)
        {
            if (ModelState.IsValid)
            {
                reminds.reminder_status = 0;
                reminds.tenant_id = null;
                reminds.landlord_id = null;

                db.reminds.Add(reminds);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reminds);
        }

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            reminds reminds = db.reminds.Find(id);
            return View(reminds);
        }

        // POST: User/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            reminds reminds = db.reminds.Find(id);
            db.reminds.Remove(reminds);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteAll()
        {
            db.Database.ExecuteSqlCommand("TRUNCATE TABLE reminds");
            db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

Views/Notification/Create.cshtml
@model AlphaZero.Models.reminds

@{
    ViewBag.Title = "Create Notification";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <div class="row">

        <div class="col-md-6 col-sm-12">
            <div class="title">
                <h4>Reminders - Create Custom Reminder</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Notification")">Notification List</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Create Customized Reminder
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>



<!-- basic table  Start -->
<div class="pd-20 card-box mb-30">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

            <div class="clearfix mb-20">
                <div class="pull-left">
                    <h4 class="text-blue h4">Create Customized Reminder Form</h4>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Variable</th>
                        <th scope="col">Content</th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <th scope="row">Reminder Title</th>
                        <td>
                            @Html.EditorFor(model => model.reminder_title, new { htmlAttributes = new { @class = "form-control", @placeholder = "Title Goes Here" } })
                            @Html.ValidationMessageFor(model => model.reminder_title, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Reminder Description</th>
                        <td>
                            @Html.EditorFor(model => model.reminder_desc, new { htmlAttributes = new { @class = "form-control", @placeholder = "Description Goes Here" } })
                            @Html.ValidationMessageFor(model => model.reminder_desc, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Reminder Date</th>
                        <td>
                            @Html.EditorFor(model => model.reminder_date, new { htmlAttributes = new { @class = "form-control date-picker" , @placeholder = "Select Date" , @type = "text"} })
                            @Html.ValidationMessageFor(model => model.reminder_date, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                </tbody>
            </table>

            <div class="card card-box text-center">
                <div class="card-body">
                    <h5 class="card-title">Actions :</h5>
                    <p class="card-text">Choose Carefully :P</p>
                    <input type="submit" value="Submit" class="btn btn-primary" />
                    <a class="btn btn-outline-warning" href="@Url.Action("Index", "Notification")" role="button">
                        Cancel
                    </a>
                </div>
            </div>
    }

</div>

Views/Notification/Delete.cshtml
@model AlphaZero.Models.reminds

@{
    ViewBag.Title = "Delete Notification";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <div class="row">

        <div class="col-md-6 col-sm-12">
            <div class="title">
                <h4>Reminders - Delete</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Notification")">Notification List</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Delete Reminder -
                        @if (Model.landlord == null && Model.tenant == null)
                        {
                            <span>Customized</span>
                        }
                        else
                        {
                            <span>@Html.DisplayFor(model => model.CombinedNames)</span>
                        }
                    </li>
                </ol>
            </nav>
        </div>

        <div class="col-md-6 col-sm-12 text-right">
            <div class="dropdown">
                <a class="btn btn-primary" href="@Url.Action("Create", "Notification")" role="button">
                    Create Customized Reminder
                </a>
            </div>
        </div>
    </div>
</div>


<!-- basic table  Start -->
<div class="pd-20 card-box mb-30">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        if (Model.landlord == null && Model.tenant == null)
        {
            <div class="clearfix mb-20">
                <div class="pull-left">
                    <h4 class="text-blue h4">Customized Reminder</h4>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.reminder_id)
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Variable</th>
                        <th scope="col">Content</th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <th scope="row">Reminder Title</th>
                        <td>
                            @Html.EditorFor(model => model.reminder_title, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.reminder_title, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Reminder Description</th>
                        <td>
                            @Html.EditorFor(model => model.reminder_desc, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.reminder_desc, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Reminder Date</th>
                        <td>
                            @Html.EditorFor(model => model.reminder_date, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.reminder_date, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                </tbody>
            </table>

            <div class="card card-box text-center">
                <div class="card-body">
                    <h5 class="card-title">Actions :</h5>
                    <p class="card-text">Choose Carefully :P</p>
                    <input type="submit" value="Delete" class="btn btn-danger" />
                    @Html.ActionLink("Back to List", "Index", new { id = Model.reminder_id }, new { @class = "btn btn-secondary" })
                </div>
            </div>
        }

        else
        {
            <div class="clearfix mb-20">
                <div class="pull-left">


                    @if (Model.landlord != null)
                    {
                        <h4 class="text-blue h4">System Reminder - Landlord Reminder</h4>
                    }
                    else if (Model.tenant != null)
                    {
                        <h4 class="text-blue h4">System Reminder - Tenant Reminder</h4>
                    }

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.reminder_id)
                    @Html.HiddenFor(model => model.landlord_id) <!-- Add this line -->
                    @Html.HiddenFor(model => model.tenant_id) <!-- Add this line -->

                </div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Variable</th>
                        <th scope="col">Content</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">Reminder Title</th>
                        <td>
                            @Html.EditorFor(model => model.reminder_title, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.reminder_title, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Reminder Description</th>
                        <td>
                            @Html.EditorFor(model => model.reminder_desc, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.reminder_desc, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Reminder Date</th>
                        <td>
                            @Html.EditorFor(model => model.reminder_date, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.reminder_date, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                </tbody>
            </table>

            <div class="card card-box text-center">
                <div class="card-body">
                    <h5 class="card-title">Actions :</h5>
                    <p class="card-text">Choose Carefully :P</p>
                    <input type="submit" value="Delete" class="btn btn-danger" />
                    @Html.ActionLink("Back to List", "Index", new { id = Model.reminder_id }, new { @class = "btn btn-secondary" })
                </div>
            </div>

        }

    }
</div>
<!-- basic table  End -->

Views/Notification/Details.cshtml
@model AlphaZero.Models.reminds

@{
    ViewBag.Title = "Details Notification";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <div class="row">

        <div class="col-md-6 col-sm-12">
            <div class="title">
                <h4>Reminders - View</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Notification")">Notification List</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        View Reminder -
                        @if (Model.landlord == null && Model.tenant == null)
                        {
                            <span>Customized</span>
                        }
                        else
                        {
                            <span>@Html.DisplayFor(model => model.CombinedNames)</span>
                        }
                    </li>
                </ol>
            </nav>
        </div>

        <div class="col-md-6 col-sm-12 text-right">
            <div class="dropdown">
                <a class="btn btn-primary" href="@Url.Action("Create", "Notification")" role="button">
                    Create Customized Reminder
                </a>
            </div>
        </div>
    </div>
</div>



    <!-- basic table  Start -->
<div class="pd-20 card-box mb-30">

    @if (Model.landlord == null && Model.tenant == null)
    {
        <div class="clearfix mb-20">
            <div class="pull-left">
                <h4 class="text-blue h4">Customized Reminder</h4>
            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Variable</th>
                    <th scope="col">Content</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">Reminder Title</th>
                    <td>@Html.DisplayFor(model => model.reminder_title)</td>
                </tr>
                <tr>
                    <th scope="row">Reminder Description</th>
                    <td>@Html.DisplayFor(model => model.reminder_desc)</td>
                </tr>
                <tr>
                    <th scope="row">Reminder Date</th>
                    <td>@Html.DisplayFor(model => model.FormattedDate)</td>
                </tr>
            </tbody>
        </table>

        <div class="card card-box text-center">
            <div class="card-body">
                <h5 class="card-title">Actions :</h5>
                <p class="card-text">Choose Carefully :P</p>
                @Html.ActionLink("Edit this Reminder", "Edit", "Notification", new { id = Model.reminder_id }, new { @class = "btn btn-warning" })
                @Html.ActionLink("Back to List", "Index", new { id = Model.reminder_id }, new { @class = "btn btn-primary" })
            </div>
        </div>
    }

    else
    {
        <div class="clearfix mb-20">
            <div class="pull-left">


                @if (Model.landlord != null)
                {
                    <h4 class="text-blue h4">System Reminder - Landlord Reminder</h4>
                }
                else if (Model.tenant != null)
                {
                    <h4 class="text-blue h4">System Reminder - Tenant Reminder</h4>
                }

            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Variable</th>
                    <th scope="col">Content</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">Reminder Title</th>
                    <td>@Html.DisplayFor(model => model.reminder_title)</td>
                </tr>
                <tr>
                    <th scope="row">Reminder Description</th>
                    <td>@Html.DisplayFor(model => model.reminder_desc)</td>
                </tr>
                <tr>
                    <th scope="row">Reminder Date</th>
                    <td>@Html.DisplayFor(model => model.FormattedDate)</td>
                </tr>

                <tr>
                    @if (Model.landlord != null)
                    {
                        <th scope="row">Name of Landlord</th>
                    }
                    else if (Model.tenant != null)
                    {
                        <th scope="row">Name of Tenant</th>
                    }
                    <td>
                        @if (Model.landlord != null)
                        {
                            <span>@Model.landlord.landlord_name</span>
                        }
                        else if (Model.tenant != null)
                        {
                            <span>@Model.tenant.tenant_name</span>
                        }

                    </td>
                </tr>
            </tbody>
        </table>

        <div class="card card-box text-center">
            <div class="card-body">
                <h5 class="card-title">Actions :</h5>
                <p class="card-text">Choose Carefully :P</p>
                @Html.ActionLink("Edit this Reminder", "Edit", "Notification", new { id = Model.reminder_id }, new { @class = "btn btn-warning" })
                @Html.ActionLink("Back to List", "Index", new { id = Model.reminder_id }, new { @class = "btn btn-primary" })
            </div>
        </div>

    }
</div>
    <!-- basic table  End -->

Views/Notification/Edit.cshtml
@model AlphaZero.Models.reminds

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@*
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>reminds</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.reminder_id)

            <div class="form-group">
                @Html.LabelFor(model => model.landlord_id, "landlord_id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("landlord_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.landlord_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.tenant_id, "tenant_id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("tenant_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.tenant_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.reminder_status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.reminder_status, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.reminder_status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.reminder_desc, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.reminder_desc, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.reminder_desc, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.reminder_title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.reminder_title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.reminder_title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.reminder_date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.reminder_date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.reminder_date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

*@






@if (Model.landlord == null && Model.tenant == null)
{
    <h2>Edit - Custom Reminder</h2>
}
else
{
    <h2>Edit - @Html.DisplayFor(model => model.CombinedNames)</h2>
}

<br />
<br />

<!-- basic table  Start -->
<div class="pd-20 card-box mb-30">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        if (Model.landlord == null && Model.tenant == null)
        {
            <div class="clearfix mb-20">
                <div class="pull-left">
                    <h4 class="text-blue h4">Customized Reminder</h4>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.reminder_id)
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Variable</th>
                        <th scope="col">Content</th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <th scope="row">Reminder Title</th>
                        <td>
                            @Html.EditorFor(model => model.reminder_title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.reminder_title, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Reminder Description</th>
                        <td>
                            @Html.EditorFor(model => model.reminder_desc, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.reminder_desc, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Reminder Date</th>
                        <td>
                            @Html.EditorFor(model => model.reminder_date, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.reminder_date, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                </tbody>
            </table>

            <div class="card card-box text-center">
                <div class="card-body">
                    <h5 class="card-title">Actions :</h5>
                    <p class="card-text">Choose Carefully :P</p>
                    @Html.ActionLink("View this Reminder", "Details", "Notification", new { id = Model.reminder_id }, new { @class = "btn btn-primary" })
                    @Html.ActionLink("Back to List", "Index", new { id = Model.reminder_id }, new { @class = "btn btn-primary" })
                </div>
            </div>
        }

        else
        {
            <div class="clearfix mb-20">
                <div class="pull-left">


                    @if (Model.landlord != null)
                    {
                        <h4 class="text-blue h4">System Reminder - Landlord Reminder</h4>
                    }
                    else if (Model.tenant != null)
                    {
                        <h4 class="text-blue h4">System Reminder - Tenant Reminder</h4>
                    }

                </div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Variable</th>
                        <th scope="col">Content</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">Reminder Title</th>
                        <td>
                            @Html.EditorFor(model => model.reminder_title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.reminder_title, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Reminder Description</th>
                        <td>
                            @Html.EditorFor(model => model.reminder_desc, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.reminder_desc, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Reminder Date</th>
                        <td>
                            @Html.EditorFor(model => model.reminder_date, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.reminder_date, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                </tbody>
            </table>

            <div class="card card-box text-center">
                <div class="card-body">
                    <h5 class="card-title">Actions :</h5>
                    <p class="card-text">Choose Carefully :P</p>
                    <input type="submit" value="Submit" class="btn btn-warning" />
                    @Html.ActionLink("Back to List", "Index", new { id = Model.reminder_id }, new { @class = "btn btn-primary" })
                </div>
            </div>

        }

    }
</div>
<!-- basic table  End -->