Models/Investor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaZero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Investor()
        {
            this.profits = new HashSet<profit>();
        }
    
        public int Investor_id { get; set; }
        public string investor_name { get; set; }
        public int investor_lotNo { get; set; }
        public double investor_holdvalue { get; set; }
        public int user_id { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<profit> profits { get; set; }
    }
}

Controllers/InvestorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AlphaZero.Models;

namespace AlphaZero.Controllers
{
    public class InvestorController : Controller
    {
        private db_roomrentalEntities db = new db_roomrentalEntities();

        // GET: Investor
        public ActionResult Index()
        {
            return View(db.users.ToList());
        }

        // GET: Investor/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user user = db.users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Investor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Investor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "user_id,user_password,user_name,user_email")] user user, [Bind(Include = "investor_id,investor_name,investor_lotNo,investor_holdvalue")] Investor investor)
        {
            if (ModelState.IsValid)
            {
                // Set the default user_type
                user.user_type = "2";

                // Save the user record
                db.users.Add(user);
                db.SaveChanges();

                // Retrieve the generated user_id
                int userId = user.user_id;

                // Assign the user_id to the investor
                investor.user_id = userId;

                // Save the investor record
                db.Investors.Add(investor);
                db.SaveChanges();

                // Call the SendCredentials method of EmailController to send the credentials
                EmailController emailController = new EmailController();
                emailController.SendCredentials(user.user_name, user.user_password, user.user_email, investor.investor_name);


                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Investor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            user user = db.users.Include(u => u.Investors).SingleOrDefault(u => u.user_id == id);

            if (user == null)
            {
                return HttpNotFound();
            }

            // Ensure there is at least one investor associated with the user
            if (user.Investors.Count == 0)
            {
                // Create a new investor and associate it with the user
                Investor investor = new Investor();
                user.Investors.Add(investor);
            }

            return View(user);
        }


        // POST: Investor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "user_id,user_password,user_name,user_email")] user user, [Bind(Include = "investor_id,investor_name,investor_lotNo,investor_holdvalue")] Investor investor)
        {
            if (ModelState.IsValid)
            {
                // Set the default user_type
                user.user_type = "2";

                // Update the user record
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();

                // Retrieve the generated user_id
                int userId = user.user_id;

                // Assign the user_id to the investor
                investor.user_id = userId;

                // Retrieve the existing investor record based on the user_id
                Investor existingInvestor = db.Investors.SingleOrDefault(i => i.user_id == user.user_id);

                // Update the investor record
                if (existingInvestor != null)
                {
                    // Update the investor record
                    existingInvestor.investor_name = investor.investor_name;
                    existingInvestor.investor_lotNo = investor.investor_lotNo;
                    existingInvestor.investor_holdvalue = investor.investor_holdvalue;

                    db.Entry(existingInvestor).State = EntityState.Modified;
                }
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Investor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            user user = db.users.Include(u => u.Investors).SingleOrDefault(u => u.user_id == id);

            if (user == null)
            {
                return HttpNotFound();
            }

            // Ensure there is at least one investor associated with the user
            if (user.Investors.Count == 0)
            {
                // Create a new investor and associate it with the user
                Investor investor = new Investor();
                user.Investors.Add(investor);
            }

            return View(user);
        }

        // POST: Investor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            user user = db.users.Find(id);
            
            // Retrieve the existing investor record based on the user_id
            Investor existingInvestor = db.Investors.SingleOrDefault(i => i.user_id == user.user_id);
            db.Investors.Remove(existingInvestor);
            db.users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Investor/Create.cshtml
@model AlphaZero.Models.user

@{
    ViewBag.Title = "Create Investor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <div class="row">

        <div class="col-md-6 col-sm-12">
            <div class="title">
                <h4>Investor - Create Investor</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Investor")">Investor List</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Create Investor
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>



<!-- basic table  Start -->
<div class="pd-20 card-box mb-30">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="clearfix mb-20">
            <div class="pull-left">
                <h4 class="text-blue h4">Create Investor Form</h4>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Variable</th>
                    <th scope="col">Content</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <th scope="row">Username : Investor</th>
                    <td>
                        @Html.EditorFor(model => model.user_name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Username of Investor Goes Here" } })
                        @Html.ValidationMessageFor(model => model.user_name, "", new { @class = "text-danger" })
                        <small>They will be using this to login into the system</small>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Password : Investor</th>
                    <td>
                        @Html.EditorFor(model => model.user_password, new { htmlAttributes = new { @class = "form-control", @placeholder = "Password of Investor Goes Here" } })
                        @Html.ValidationMessageFor(model => model.user_password, "", new { @class = "text-danger" })
                        <small>They will be using this to login into the system</small>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Email : Investor</th>
                    <td>
                        @Html.EditorFor(model => model.user_email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email of Investor Goes Here", @type = "email" } })
                        @Html.ValidationMessageFor(model => model.user_email, "", new { @class = "text-danger" })
                    </td>
                </tr>

                <tr>
                    <th scope="row">Below is <code>.For Admin Use</code></th>
                    <td></td>
                </tr>

                <tr>
                    <th scope="row">Investor Name</th>
                    <td>
                        @Html.EditorFor(model => model.Investors.First().investor_name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Investor Name Goes Here", @type = "text" } })
                        @Html.ValidationMessageFor(model => model.Investors.First().investor_name, "", new { @class = "text-danger" })
                    </td>
                </tr>

                <tr>
                    <th scope="row">Investor Lot Number</th>
                    <td>
                        @Html.EditorFor(model => model.Investors.First().investor_lotNo, new { htmlAttributes = new { @class = "form-control", @placeholder = "Investor Lot Number Goes Here", @type = "number" } })
                        @Html.ValidationMessageFor(model => model.Investors.First().investor_lotNo, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <th scope="row">Investor Hold Value</th>
                    <td>
                        @Html.EditorFor(model => model.Investors.First().investor_holdvalue, new { htmlAttributes = new { @class = "form-control", @placeholder = "Investor Hold Value Goes Here", @type = "number", step = "0.01" } })
                        @Html.ValidationMessageFor(model => model.Investors.First().investor_holdvalue, "", new { @class = "text-danger" })
                    </td>
                </tr>
            </tbody>
        </table>

        <div class="card card-box text-center">
            <div class="card-body">
                <h5 class="card-title">Actions :</h5>
                <p class="card-text">Choose Carefully :P</p>
                
                <a class="btn btn-info" data-toggle="modal" data-target="#confirmation-modal" role="button">
                    Submit
                </a>

                <a class="btn btn-outline-warning" href="@Url.Action("Index", "Investor")" role="button">
                    Cancel
                </a>
            </div>
        </div>

        <div class="modal fade" id="confirmation-modal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-body text-center font-18">
                        <h4 class="padding-top-30 mb-30 weight-500">Are you sure you want to create this Investor?</h4>
                        <h5 class="mb-30 weight-500">An Email Will be Sent to this Investor</h5>
                        <div class="padding-bottom-30 row" style="max-width: 170px; margin: 0 auto;">
                            <div class="col-6">
                                <button type="button" class="btn btn-secondary border-radius-100 btn-block confirmation-btn" data-dismiss="modal"><i class="fa fa-times"></i></button>
                                NO
                            </div>
                            <div class="col-6">
                                    <button type="submit" class="btn btn-primary border-radius-100 btn-block confirmation-btn">
                                    <i class="fa fa-check"></i>
                                    </button>
                                    YES
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }

</div>

Views/Investor/Delete.cshtml
@model AlphaZero.Models.user

@{
    ViewBag.Title = "Delete Investor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}






<div class="page-header">
    <div class="row">

        <div class="col-md-6 col-sm-12">
            <div class="title">
                <h4>Investor - Delete</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Investor")">Investor List</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Delete Investor
                    </li>
                </ol>
            </nav>
        </div>

        <div class="col-md-6 col-sm-12 text-right">
            <div class="dropdown">
                <a class="btn btn-primary" href="@Url.Action("Create", "Investor")" role="button">
                    Create Investor
                </a>
            </div>
        </div>
    </div>
</div>


<!-- basic table  Start -->
<div class="pd-20 card-box mb-30">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="clearfix mb-20">
            <div class="pull-left">
                <h4 class="text-blue h4">Investor Credentials</h4>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Variable</th>
                    <th scope="col">Content</th>
                </tr>
            </thead>

            <tbody>

                <tr>
                    <th scope="row">Username : Investor</th>
                    <td>
                        @Html.EditorFor(model => model.user_name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.user_name, "", new { @class = "text-danger" })
                        <small>They will be using this to login into the system</small>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Email : Investor</th>
                    <td>
                        @Html.EditorFor(model => model.user_email, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.user_email, "", new { @class = "text-danger" })
                    </td>
                </tr>

                <tr>
                    <th scope="row">Below is <code>.For Admin Use</code></th>
                    <td></td>
                </tr>

                <tr>
                    <th scope="row">Investor Name</th>
                    <td>
                        @Html.EditorFor(model => model.Investors.First().investor_name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Investors.First().investor_name, "", new { @class = "text-danger" })
                    </td>
                </tr>

                <tr>
                    <th scope="row">Investor Lot Number</th>
                    <td>
                        @Html.EditorFor(model => model.Investors.First().investor_lotNo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Investors.First().investor_lotNo, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <th scope="row">Investor Hold Value</th>
                    <td>
                        @Html.EditorFor(model => model.Investors.First().investor_holdvalue, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Investors.First().investor_holdvalue, "", new { @class = "text-danger" })
                    </td>
                </tr>
            </tbody>
        </table>

        <div class="card card-box text-center">
            <div class="card-body">
                <h5 class="card-title">Actions :</h5>
                <p class="card-text">Choose Carefully :P</p>
                <input type="submit" value="Delete" class="btn btn-danger" />
                @Html.ActionLink("Back to List", "Index", new { id = Model.user_id }, new { @class = "btn btn-secondary" })
            </div>
        </div>
    } 
</div>

Views/Investor/Details.cshtml
@model AlphaZero.Models.user

@{
    ViewBag.Title = "Details Investor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <div class="row">

        <div class="col-md-6 col-sm-12">
            <div class="title">
                <h4>Investor - View</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Investor")">Investor List</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        View Investor - <span>@Html.DisplayFor(model => model.Investors.First().investor_name)</span>

                    </li>
                </ol>
            </nav>
        </div>

        <div class="col-md-6 col-sm-12 text-right">
            <div class="dropdown">
                <a class="btn btn-primary" href="@Url.Action("Create", "Investor")" role="button">
                    Create Investor
                </a>
            </div>
        </div>
    </div>
</div>

<!-- basic table  Start -->
<div class="pd-20 card-box mb-30">

    <div class="clearfix mb-20">
        <div class="pull-left">
            <h4 class="text-blue h4">Investor Credentials</h4>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Variable</th>
                <th scope="col">Content</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">Investor Username</th>
                <td>@Html.DisplayFor(model => model.user_name)</td>
            </tr>
            <tr>
                <th scope="row">Investor Email</th>
                <td>@Html.DisplayFor(model => model.user_email)</td>
            </tr>
            <tr>
                <th scope="row">Investor Name</th>
                <td>@Html.DisplayFor(model => model.Investors.First().investor_name)</td>
            </tr>
            <tr>
                <th scope="row">Investor Hold Value</th>
                <td>@Html.DisplayFor(model => model.Investors.First().investor_holdvalue)</td>
            </tr>
            <tr>
                <th scope="row">Investor Lot Number</th>
                <td>@Html.DisplayFor(model => model.Investors.First().investor_lotNo)</td>
            </tr>
        </tbody>
    </table>

    <div class="card card-box text-center">
        <div class="card-body">
            <h5 class="card-title">Actions :</h5>
            <p class="card-text">Choose Carefully :P</p>
            @Html.ActionLink("Edit this Investor", "Edit", "Investor", new { id = Model.user_id }, new { @class = "btn btn-warning" })
            @Html.ActionLink("Back to List", "Index", new { id = Model.user_id }, new { @class = "btn btn-primary" })
        </div>
    </div>


</div>

Views/Investor/Edit.cshtml
@model AlphaZero.Models.user

@{
    ViewBag.Title = "Edit Investor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <div class="row">

        <div class="col-md-6 col-sm-12">
            <div class="title">
                <h4>Investor - Edit</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Investor")">Investor List</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Edit Investor - <span>@Html.DisplayFor(model => model.Investors.First().investor_name)</span>

                    </li>
                </ol>
            </nav>
        </div>

        <div class="col-md-6 col-sm-12 text-right">
            <div class="dropdown">
                <a class="btn btn-primary" href="@Url.Action("Create", "Investor")" role="button">
                    Create Investor
                </a>
            </div>
        </div>
    </div>
</div>


<!-- basic table  Start -->
<div class="pd-20 card-box mb-30">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="clearfix mb-20">
            <div class="pull-left">
                <h4 class="text-blue h4">Edit Investor Credentials</h4>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.user_id)
            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Variable</th>
                    <th scope="col">Content</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <th scope="row">Username : Investor</th>
                    <td>
                        @Html.EditorFor(model => model.user_name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Username of Investor Goes Here" } })
                        @Html.ValidationMessageFor(model => model.user_name, "", new { @class = "text-danger" })
                        <small>This will change their login credentials, an email will be sent to notify them</small>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Password : Investor</th>
                    <td>
                        @Html.EditorFor(model => model.user_password, new { htmlAttributes = new { @class = "form-control", @placeholder = "Password of Investor Goes Here" } })
                        @Html.ValidationMessageFor(model => model.user_password, "", new { @class = "text-danger" })
                        <small>This will change their login credentials, an email will be sent to notify them</small>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Email : Investor</th>
                    <td>
                        @Html.EditorFor(model => model.user_email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email of Investor Goes Here", @type = "email" } })
                        @Html.ValidationMessageFor(model => model.user_email, "", new { @class = "text-danger" })
                    </td>
                </tr>

                <tr>
                    <th scope="row">Below is <code>.For Admin Use</code></th>
                    <td></td>
                </tr>

                <tr>
                    <th scope="row">Investor Name</th>
                    <td>
                        @Html.EditorFor(model => model.Investors.First().investor_name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Investor Name Goes Here", @type = "text" } })
                        @Html.ValidationMessageFor(model => model.Investors.First().investor_name, "", new { @class = "text-danger" })
                    </td>
                </tr>

                <tr>
                    <th scope="row">Investor Lot Number</th>
                    <td>
                        @Html.EditorFor(model => model.Investors.First().investor_lotNo, new { htmlAttributes = new { @class = "form-control", @placeholder = "Investor Lot Number Goes Here", @type = "number" } })
                        @Html.ValidationMessageFor(model => model.Investors.First().investor_lotNo, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <th scope="row">Investor Hold Value</th>
                    <td>
                        @Html.EditorFor(model => model.Investors.First().investor_holdvalue, new { htmlAttributes = new { @class = "form-control", @placeholder = "Investor Hold Value Goes Here", @type = "number", step = "0.01" } })
                        @Html.ValidationMessageFor(model => model.Investors.First().investor_holdvalue, "", new { @class = "text-danger" })
                    </td>
                </tr>
            </tbody>
        </table>

        <div class="card card-box text-center">
            <div class="card-body">
                <h5 class="card-title">Actions :</h5>
                <p class="card-text">Choose Carefully :P</p>
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-outline-warning" href="@Url.Action("Index", "Investor")" role="button">
                    Cancel
                </a>
            </div>
        </div>
    }

</div>

Views/Investor/Index.cshtml
@model IEnumerable<AlphaZero.Models.user>

@{
    ViewBag.Title = "Investors";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <div class="row">

        <div class="col-md-6 col-sm-12">
            <div class="title">
                <h4>Investors - View</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="breadcrumb-item">Manage Users</li>
                    <li class="breadcrumb-item active" aria-current="page">Investors</li>
                </ol>
            </nav>
        </div>
    </div>
</div>


<div class="pd-20 card-box mb-30">
    <div class="clearfix mb-20">
        <div class="pull-left">
            <h4 class="text-blue h4">Investors</h4>
            <p>Investors registered to the <code>.system</code> :P</p>
        </div>
        <div class="pull-right">
            <a href="@Url.Action("Create", "Investor")" class="btn btn-primary btn-sm scroll-click" role="button">
                <i class="icon-copy fi-torso-business"></i> Create Investor
            </a>
        </div>
    </div>
    <div class="pb-20">
        <table class="table hover multiple-select-row data-table-export nowrap">
            <thead>
                <tr>
                    <th class="table-plus datatable-nosort">Investor Username</th>
                    <th>Name</th>
                    <th>Lot Number</th>
                    <th>Hold Value</th>
                    <th class="datatable-nosort">Action</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    if (item.Investors.Any())
                    {

                        <tr>
                            <td class="table-plus">
                                <span>@Html.DisplayFor(modelItem => item.user_name)</span>
                            </td>

                            <td>@Html.DisplayFor(modelItem => item.Investors.First().investor_name)</td>
                            <td>@Html.DisplayFor(modelItem => item.Investors.First().investor_lotNo)</td>
                            <td>@Html.DisplayFor(modelItem => item.Investors.First().investor_holdvalue)</td>
                            <td>
                                <div class="dropdown">
                                    <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                                        <i class="dw dw-more"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                                        <a class="dropdown-item" href="@Url.Action("Details", "Investor", new { id = item.user_id })">
                                            <i class="dw dw-eye"></i> View
                                        </a>
                                        <a class="dropdown-item" href="@Url.Action("Edit", "Investor", new { id = item.user_id })">
                                            <i class="dw dw-edit2"></i> Edit
                                        </a>
                                        <a class="dropdown-item" href="@Url.Action("Delete", "Investor", new { id = item.user_id })">
                                            <i class="dw dw-delete-3"></i> Delete
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>