Models/sysConfig.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaZero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysConfig
    {
        public string category { get; set; }
        public string value { get; set; }
    }
}

Controllers/sysConfigsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AlphaZero.Models;

namespace AlphaZero.Controllers
{
    public class sysConfigsController : Controller
    {
        private db_roomrentalEntities db = new db_roomrentalEntities();

        // GET: sysConfigs
        public ActionResult Index()
        {
            var sysConfigs = db.sysConfigs.ToList();
            return View(sysConfigs);
        }


        [HttpPost]
        public ActionResult UpdateConfig(string bankAcc, string bankName)
        {
            // Update the sysConfig values based on the submitted form values
            UpdateSysConfigValue("bankAcc", bankAcc);
            UpdateSysConfigValue("bankName", bankName);

            // Redirect back to the Index action
            return RedirectToAction("Index");
        }

        private void UpdateSysConfigValue(string category, string value)
        {
            var existingConfig = db.sysConfigs.SingleOrDefault(c => c.category == category);

            if (existingConfig != null)
            {
                existingConfig.value = value;
                db.SaveChanges();
            }
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/sysConfigs/Index.cshtml
@model IEnumerable<AlphaZero.Models.sysConfig>

@{
    ViewBag.Title = "System Configuration";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="title">
                <h4>System Configuration</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">System Configuration</li>
                </ol>
            </nav>
        </div>
    </div>
</div>

<!-- basic table  Start -->
<div class="pd-20 card-box mb-30">
    <div class="clearfix mb-20">
        <div class="pull-left">
            <h4 class="text-blue h4">System Settings</h4>
        </div>
    </div>

    @using (Html.BeginForm("UpdateConfig", "sysConfigs", FormMethod.Post))
    {

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Category</th>
                    <th scope="col">Value</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">

                            @if (item.category == "bankAcc")
                            {
                                <text>Bank Account</text>
                            }
                            else if (item.category == "bankName")
                            {
                                <text>Bank Name</text>
                            }

                        </th>

                        <td>
                            @if (item.category == "bankAcc")
                            {
                                @Html.TextBox("bankAcc", item.value, new { type = "number", @class = "form-control", @placeholder = "Bank Account Number Goes Here" })
                            }
                            else if (item.category == "bankName")
                            {
                                @Html.TextBox("bankName", item.value, new { type = "text", @class = "form-control", @placeholder = "Bank Account Name Goes Here" })
                            }

                        </td>
                        <td>
                            <input type="submit" value="Update" class="btn btn-primary"/>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>